/* BROCHURES */
export const GET_BROCHURES = "GET_BROCHURES"
export const GET_BROCHURES_SUCCESS = "GET_BROCHURES_SUCCESS"
export const GET_BROCHURES_FAIL = "GET_BROCHURES_FAIL"

/* BROCHURES DETAIL*/
export const GET_BROCHURE_DETAIL = "GET_BROCHURE_DETAIL"
export const GET_BROCHURE_DETAIL_SUCCESS = "GET_BROCHURE_DETAIL_SUCCESS"
export const GET_BROCHURE_DETAIL_FAIL = "GET_BROCHURE_DETAIL_FAIL"
/**
 * Delete BROCHURES
 */
export const DELETE_BROCHURE = "DELETE_BROCHURE"
export const DELETE_BROCHURE_SUCCESS = "DELETE_BROCHURE_SUCCESS"
export const DELETE_BROCHURE_FAIL = "DELETE_BROCHURE_FAIL"
